module.exports = {
    listSchema: {
        tags: ['order'],
        summary: '订单列表（管理端/小程序）',
        querystring: {
            type: 'object',
            properties: {
                page: { type: 'integer', default: 1 },
                pageSize: { type: 'integer', default: 20 },
                userid: { type: 'string' },
                type: { type: 'integer', description: '1上门 2邮寄' },
                way: { type: 'integer', enum: [1, 2, 3], description: '收款方式：1微信 2支付宝 3银行卡' },
                status: { type: 'integer', enum: [10, 20, 30, 40, 50, 60], description: '订单状态：10已下单 20已签收 30已报价 40已确认 50已返款 60已完成' },
                keyword: { type: 'string', description: '手机号/单号/快递公司/备注 关键词' },
                startAt: { type: 'string', description: '创建时间开始（ISO）' },
                endAt: { type: 'string', description: '创建时间结束（ISO）' },
            },
        },
    },
    detailSchema: {
        tags: ['order'],
        summary: '订单详情',
        params: {
            type: 'object',
            required: ['id'],
            properties: {
                id: { type: 'integer' },
            },
        },
    },
    createSchema: {
        tags: ['order'],
        summary: '创建订单',
        body: {
            type: 'object',
            required: ['phone'],
            properties: {
                nums: { type: 'integer', minimum: 1, description: '与回收明细二选一：有 devices 时可由服务端汇总数量' },
                price: { type: ['string', 'null'], description: '可选，未报价可为空' },
                phone: { type: 'string' },
                remark: { type: 'string' },
                way: { type: 'integer', enum: [1, 2, 3], description: '收款方式：1微信 2支付宝 3银行卡' },
                payee_name: { type: 'string', description: '收款人姓名（银行卡必填）' },
                wechat_account: { type: 'string', description: '微信收款账号（way=1 建议填写）' },
                alipay_account: { type: 'string', description: '支付宝收款账号（way=2 建议填写）' },
                bank_name: { type: 'string', description: '开户行名称（way=3 必填）' },
                bank_card_no: { type: 'string', description: '银行卡号（way=3 必填）' },
                userid: { type: 'string', description: '管理员代下单可传；小程序端自动取token' },
                type: { type: 'integer', description: '1上门 2邮寄' },
                visit_time: { type: 'string' },
                tracking_number: { type: 'string' },
                express_company: { type: 'string', description: '快递公司名称（字符串）' },
                areas: { type: 'string' },
                hourse_number: { type: 'string' },
                status: { type: 'integer', enum: [10, 20, 30, 40, 50, 60], description: '订单状态：10已下单 20已签收 30已报价 40已确认 50已返款 60已完成' },
                remark_images: {
                    oneOf: [
                        { type: 'array', items: { type: 'string' } },
                        { type: 'string' },
                        { type: 'object', additionalProperties: true },
                        { type: 'null' },
                    ],
                    description: '备注图片，兼容数组/字符串/对象/null',
                },
                devices: {
                    type: 'array',
                    description: '回收明细：机型/内存/整机|单板/数量',
                    items: {
                        type: 'object',
                        required: ['model', 'memory', 'qty'],
                        properties: {
                            model: { type: 'string' },
                            memory: { type: 'string' },
                            unit: { type: 'string', enum: ['whole', 'board'] },
                            qty: { type: 'integer', minimum: 1 },
                            price: { type: ['string', 'null'], description: '该型号单独价格（可空）' },
                        },
                    },
                },
            },
        },
    },
    updateSchema: {
        tags: ['order'],
        summary: '更新订单',
        params: {
            type: 'object',
            required: ['id'],
            properties: {
                id: { type: 'integer' },
            },
        },
        body: {
            type: 'object',
            properties: {
                nums: { type: 'integer', minimum: 1 },
                price: { type: ['string', 'null'], description: '可选，未报价可为空' },
                phone: { type: 'string' },
                remark: { type: 'string' },
                way: { type: 'integer', enum: [1, 2, 3], description: '收款方式：1微信 2支付宝 3银行卡' },
                payee_name: { type: 'string', description: '收款人姓名（银行卡必填）' },
                wechat_account: { type: 'string', description: '微信收款账号（way=1 建议填写）' },
                alipay_account: { type: 'string', description: '支付宝收款账号（way=2 建议填写）' },
                bank_name: { type: 'string', description: '开户行名称（way=3 必填）' },
                bank_card_no: { type: 'string', description: '银行卡号（way=3 必填）' },
                type: { type: 'integer' },
                visit_time: { type: 'string' },
                tracking_number: { type: 'string' },
                express_company: { type: 'string' },
                areas: { type: 'string' },
                hourse_number: { type: 'string' },
                status: { type: 'integer', enum: [10, 20, 30, 40, 50, 60], description: '订单状态：10已下单 20已签收 30已报价 40已确认 50已返款 60已完成' },
                remark_images: {
                    oneOf: [
                        { type: 'array', items: { type: 'string' } },
                        { type: 'string' },
                        { type: 'object', additionalProperties: true },
                        { type: 'null' },
                    ],
                    description: '备注图片，兼容数组/字符串/对象/null',
                },
                devices: {
                    type: 'array',
                    items: {
                        type: 'object',
                        required: ['model', 'memory', 'qty'],
                        properties: {
                            model: { type: 'string' },
                            memory: { type: 'string' },
                            unit: { type: 'string', enum: ['whole', 'board'] },
                            qty: { type: 'integer', minimum: 1 },
                            price: { type: ['string', 'null'], description: '该型号单独价格（可空）' },
                        },
                    },
                },
            },
        },
    },
    deleteSchema: {
        tags: ['order'],
        summary: '删除订单（软删）',
        params: {
            type: 'object',
            required: ['id'],
            properties: {
                id: { type: 'integer' },
            },
        },
    },
}
